CREATE DATABASE enterprise DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE enterprise;


CREATE TABLE USERS (
    USERS_ID int NOT NULL AUTO_INCREMENT,
    LOGON_ID varchar(255),
    PASSWORD varchar(255),
    PRIMARY KEY(USERS_ID)
);

CREATE TABLE ADDRESS (
    ADDRESS_ID int NOT NULL AUTO_INCREMENT,
    USERS_ID int,
    FIRSTNAME varchar(255),
    LASTNAME varchar(255),
    ADDRESS varchar(255),
    CITY varchar(255),
    STATE varchar(255),
    ZIPCODE varchar(255),
    FOREIGN KEY(USERS_ID)
    REFERENCES USERS(USERS_ID),
    PRIMARY KEY(ADDRESS_ID)
);

CREATE TABLE ORDERS(
    ORDERS_ID int NOT NULL AUTO_INCREMENT,
    USERS_ID int,
    ADDRESS_ID int,
    TOTALPRICE double,
    ORDERDATE datetime,
    FOREIGN KEY(USERS_ID)
    REFERENCES USERS(USERS_ID),
    FOREIGN KEY(ADDRESS_ID)
    REFERENCES ADDRESS(ADDRESS_ID),
    PRIMARY KEY(ORDERS_ID)
);


CREATE TABLE PRODUCTS(
    PRODUCTS_ID int NOT NULL AUTO_INCREMENT,
    PARTNUMBER varchar(255),
    NAME varchar(255),
    PRICE double,
    IMAGE longblob,
    PRIMARY KEY(PRODUCTS_ID)
);

CREATE TABLE ORDERITEMS(
    ORDERITEMS_ID int NOT NULL AUTO_INCREMENT,
    ORDERS_ID int,
    PRODUCTS_ID int,
    QUANTITY int,
    TOTALPRICE double,
    FOREIGN KEY(ORDERS_ID)
    REFERENCES ORDERS(ORDERS_ID),
    FOREIGN KEY(PRODUCTS_ID)
    REFERENCES PRODUCTS(PRODUCTS_ID),
    PRIMARY KEY(ORDERITEMS_ID)
);